# Generated by Django 4.1.2 on 2023-08-24 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('front_image', models.ImageField(upload_to='images')),
                ('left_image', models.ImageField(upload_to='images')),
                ('right_image', models.ImageField(upload_to='images')),
                ('upper_image', models.ImageField(upload_to='images')),
                ('lower_image', models.ImageField(upload_to='images')),
                ('front_ann', models.FileField(upload_to='files')),
                ('left_ann', models.FileField(upload_to='files')),
                ('right_ann', models.FileField(upload_to='files')),
                ('upper_ann', models.FileField(upload_to='files')),
                ('lower_ann', models.FileField(upload_to='files')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
